# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  overrideGpg: true

gui:
  nerdFontsVersion: "3"
  scrollHeight: 5

os:
  editPreset: zed

keybinding:
  universal:
    prevBlock-alt: "" # no-op to free 'h'
    jumpToBlock:
      - "1"
      - "c"
      - "h"
      - "t"
      - "$"
  branches:
    checkoutBranchByName: s
  commits:
    setFixupMessage: "" # no-op to free 's'

customCommands:
  - key: "G"
    context: "localBranches"
    description: "View MR on GitLab"
    command: "glab mr view {{.SelectedLocalBranch.Name}} --web"
    loadingText: "Opening MR..."
