theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
shell = ["/opt/homebrew/bin/fish", "-c"]
# Sync clipboard with system clipboard
default-yank-register = "+"
bufferline = "multiple"
scrolloff = 8
true-color = true  
undercurl = true
jump-label-alphabet = "aoeuhtns'qjkmwvz"
end-of-line-diagnostics = "error"
# rulers = [80, 120]
completion-replace = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.auto-save]
after-delay.timeout = 500
after-delay.enable = true

[keys.normal]
X = "select_line_above"
c = "change_selection_noyank"
ret = "goto_word"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
"#" = "toggle_comments"
S-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

C-c = "no_op"
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]
g = { h = ["insert_at_line_start", "normal_mode"] }
S-d = "delete_char_backward"
C-h = ":open %sh{harpoon get 1}"
C-t = ":open %sh{harpoon get 2}"
C-n = ":open %sh{harpoon get 3}"
C-s = ":open %sh{harpoon get 4}"

[keys.select]
X = "select_line_above"
c = "change_selection_noyank"
ret = "extend_to_word"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
"#" = "toggle_comments"
S-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
S-tab = "move_parent_node_start"

C-c = "normal_mode"

[keys.normal.space]
space = "file_picker"
q = ":quit"
c = [":insert-output clear && chezmoi apply", ":config-reload", ":reload-all", ":redraw"]
S-c = ":open %sh{echo (chezmoi source-path)/private_dot_config/helix/config.toml}"
m = ":sh harpoon hook %{buffer_name}"
S-m = ":open %sh{harpoon edit}"
B = ":sh git log -n 5 --format='format:%%h (%%an: %%ar) %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"
f = ":insert-output lazygit --filter \"%{buffer_name}\""
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]
l = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
  ":reload-all"
]
