[metadata]
name = "gitter"
requirements = ["fd", "git"]
description = """
A channel to select from git repositories on your local machine.

Uses the `repos` fish function to find regular and bare git repositories.
"""

[source]
command = "repos"
display = "{split:/:-1}"
# output = "git_worktree_select '{}'"

[preview]
command = "git -C '{}' log -n 200 --pretty=medium --all --graph --color"

# [keybindings]
# enter = "actions:open"
#
# [actions.open]
# description = "Open the repository in editor"
# command = "git_worktree_select {}"
# mode = "execute"
